export const config = {
  PORT: Number(process.env.PORT ?? 3000),
  DATABASE_PATH: './data/attendance.sqlite',
  TIMEZONE: 'Asia/Riyadh',
  UNIFI_WEBHOOK_SECRET: 'Unifi-secret-2026',
  UNIFI_BASE_URL: 'https://192.168.8.1',
  UNIFI_API_TOKEN: '5wnFjU6RoXNMFnT9gx3b9K_QKVNlTubJ',
  JISR_BASE_URL: 'https://apis.jisr.net/api',
  JISR_SLUG: 'zood',
  JISR_API_KEY: 'kbmnySRFFoiGJ_2zW8kwcg',
  JISR_API_SECRET: 'gF5vi5OkV-WoPzv1I0MilA',
  DASHBOARD_PASSWORD: 'gF5vi5OkV-WoPzv1I0MilA',
  EMPLOYEE_REFRESH_MS: 300_000,
  REQUEST_TIMEOUT_MS: 10_000,
  WORKER_INTERVAL_MS: 1_000,
  REORDER_WINDOW_MS: 5_000,
  MAX_FUTURE_SKEW_MS: 60_000,
  MAX_EVENT_AGE_MS: 604_800_000,
  RECONCILE_INTERVAL_MS: 30_000,
  SESSION_TTL_MS: 43_200_000,
  READER_DIRECTIONS: {} as Record<string, 'in' | 'out'>,
};
export type Config = typeof config;
