import { describe, expect, it } from 'vitest';
import { config } from './config.js';
import type { Confirmation, Employee, JisrGateway, Punch, Submission } from './domain.js';
import { normalize, parseTimestamp } from './normalize.js';
import { Store } from './store.js';
import { Worker } from './worker.js';
import { createApp } from './app.js';
import { JisrClient } from './jisr.js';

const now = Date.parse('2026-09-13T08:20:30Z');
const event = (time: string, direction: string, user = 'u1', credential = 'FACE') => ({ id: 'access.unlocks.location_unlocked', device: direction === 'entered' ? 'entry-reader' : 'exit-reader', device_name: `Office-${direction}`, location_name: `Office-${direction}`, user, user_name: 'Exact Person', time, direction, credential_type: credential, admin: '', emergency_mode: '' });
class Fake implements JisrGateway {
  submissions: Punch[] = [];
  employeesList: Employee[] = [{ id: 'e1', code: '007', email: null, name: 'Exact Person', active: true }];
  async employees() { return this.employeesList; }
  async prepare() {}
  async submit(punch: Punch): Promise<Submission> { this.submissions.push(punch); return { outcome: 'accepted', message: 'accepted' }; }
  async confirm(): Promise<Confirmation> { return { outcome: 'confirmed', message: 'confirmed' }; }
}
describe('production attendance flow', () => {
  it('parses Unix seconds exactly and rejects timezone-free timestamps', () => { expect(parseTimestamp('1789287617')).toBe(Date.parse('2026-09-13T08:20:17Z')); expect(parseTimestamp('2026-09-13T11:20:17')).toBeNull(); });
  it('uses explicit exited and entered directions from real UniFi alarm payloads', () => { expect(normalize(event('1789287617','entered'),now,config).direction).toBe('in'); expect(normalize(event('1789287595','exited'),now,config).direction).toBe('out'); });
  it('skips remote unlocks and retains malformed deliveries independently', () => { expect(normalize(event('1789287617','entered','u1','MOBILE_BUTTON'),now,config).status).toBe('skipped'); const s=new Store(':memory:'); expect(s.ingest('{',now,config).eventIds).toHaveLength(1); expect(s.ingest('{bad',now+1,config).eventIds).toHaveLength(1); expect(s.counts().held).toBe(2); s.close(); });
  it('stores every event, processes all batch items, preserves leading-zero employee code and source instant', async () => { const s=new Store(':memory:'); const f=new Fake(); let clock=now; const w=new Worker(s,f,{...config,REORDER_WINDOW_MS:0},()=>clock); s.ingest(JSON.stringify({events:[event('1789287595','exited'),event('1789287617','entered')]}),now,{...config,REORDER_WINDOW_MS:0}); await w.tick(); expect(f.submissions).toHaveLength(1); clock+=config.RECONCILE_INTERVAL_MS; await w.tick(); expect(s.counts().confirmed).toBe(1); clock+=5_001; await w.tick(); expect(f.submissions).toHaveLength(2); expect(f.submissions[1]).toMatchObject({emp_code:'007',punch_time:'2026-09-13T08:20:17.000Z'}); s.close(); });
  it('never guesses ambiguous people and ignores repeated same-direction movement', async () => { const s=new Store(':memory:'); const f=new Fake(); f.employeesList.push({id:'e2',code:'8',email:null,name:'Exact Person',active:true}); const w=new Worker(s,f,{...config,REORDER_WINDOW_MS:0},()=>now); s.ingest(JSON.stringify(event('1789287595','exited')),now,{...config,REORDER_WINDOW_MS:0}); await w.tick(); expect(s.counts().held).toBe(1); expect(f.submissions).toHaveLength(0); s.close(); });
  it('submits only one punch for repeated same-direction source events', async () => { const s=new Store(':memory:'); const f=new Fake(); let clock=now; const localConfig={...config,REORDER_WINDOW_MS:0}; const w=new Worker(s,f,localConfig,()=>clock); s.ingest(JSON.stringify(event('1789287595','exited')),now,localConfig); await w.tick(); clock+=config.RECONCILE_INTERVAL_MS; await w.tick(); s.ingest(JSON.stringify(event('1789287600','exited')),now,localConfig); await w.tick(); expect(f.submissions).toHaveLength(1); expect(s.counts().skipped).toBe(1); s.close(); });
  it('matches a unique two-part UniFi name but refuses generic one-token names', () => { const s=new Store(':memory:'); s.replaceEmployees([{id:'a',code:'1',email:null,name:'Rafat Shabaan AbouRabie',active:true},{id:'b',code:'2',email:null,name:'Mohammed Fahad Alghammas',active:true}],now); s.ingest(JSON.stringify(event('1789287595','exited','u1')),now,{...config,REORDER_WINDOW_MS:0}); const specific=s.event(1)!; specific.name='Rafat Abou Rabie'; expect(s.match(specific)?.id).toBe('a'); specific.name='Mohammed Mohi'; expect(s.match(specific)).toBeNull(); s.close(); });
  it('does not resend a submission whose outcome is unknown after restart', () => { const s=new Store(':memory:'); s.db.prepare("INSERT INTO deliveries(receivedAt,raw) VALUES(?,?)").run(now,'{}'); s.ingest(JSON.stringify(event('1789287595','exited')),now,{...config,REORDER_WINDOW_MS:0}); const row=s.ready(now)[0]; s.beginSend(row,{id:row.id,emp_code:'1',terminal_sn:'x',punch_time:'2026-09-13T08:19:55.000Z'},now); s.recover(now+1); expect(s.event(row.id)?.status).toBe('uncertain'); expect(s.ready(now+2)).toHaveLength(0); s.close(); });
  it('protects the dashboard and authenticates both webhook routes without exposing secrets', async () => { const s=new Store(':memory:'); const w=new Worker(s,new Fake(),config,()=>now); const app=createApp(s,w,config,'missing'); expect((await app.request('/api/admin/summary')).status).toBe(401); expect((await app.request('/api/webhook/unifi',{method:'POST',body:'{}'})).status).toBe(401); const accepted=await app.request('/api/webhooks/unifi',{method:'POST',headers:{Authorization:`Bearer ${config.UNIFI_WEBHOOK_SECRET}`},body:JSON.stringify(event('1789287617','entered'))}); expect(accepted.status).toBe(202); const login=await app.request('/api/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:config.DASHBOARD_PASSWORD})}); expect(login.status).toBe(200); const session=login.headers.get('set-cookie')!; expect((await app.request('/api/admin/summary',{headers:{cookie:session}})).status).toBe(200); s.close(); });
  it('uses the verified Jisr auth route, token header, and attendance batch envelope', async () => { const calls:{url:string,init:RequestInit}[]=[]; const fetcher=async(input:any,init:RequestInit={})=>{calls.push({url:String(input),init}); if(String(input).endsWith('/openapi/v1/auth')) return new Response(JSON.stringify({success:true,data:'token'}),{status:200}); return new Response(JSON.stringify({success:true,message:'accepted'}),{status:200});}; const client=new JisrClient(config,fetcher as typeof fetch); await client.prepare(); await client.submit({id:9,emp_code:'007',terminal_sn:'reader',punch_time:'2026-09-13T08:20:17.000Z'}); expect(calls[0].url).toBe(`${config.JISR_BASE_URL}/openapi/v1/auth`); expect(calls[0].init.method).toBe('POST'); expect((calls[1].init.headers as Record<string,string>)['Access-Token']).toBe('token'); expect(JSON.parse(String(calls[1].init.body))).toEqual({data:[{id:9,emp_code:'007',terminal_sn:'reader',punch_time:'2026-09-13T08:20:17.000Z'}]}); });
});
